name: Build docker image

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      packages: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: output

      - name: Read version
        id: version
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/trino-k8s
          docker build -t $IMAGE_NAME:$VERSION .
          docker push $IMAGE_NAME:$VERSION

          # # Optionally also tag "latest" for main
          # if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          #   docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest
          #   docker push $IMAGE_NAME:latest
          # fi
