name: Release with Maven

on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types: ["completed"]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      actions: read
      contents: write
      packages: write
      issues: read
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: output

      - name: Read version
        id: version
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Configure Git user
        run: |
          git config user.name "${{ github.event.head_commit.committer.name }}"
          git config user.email "${{ github.event.head_commit.committer.email }}"
